// Copyright © 2019 Binance
//
// This file is part of Binance. The full Binance copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: schnorr-signing.proto

package signing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a BROADCAST message sent to all parties during Round 1 of the EdDSA TSS pre-signing protocol.
type PreSignRound1Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commitment    []byte                 `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSignRound1Message) Reset() {
	*x = PreSignRound1Message{}
	mi := &file_schnorr_signing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSignRound1Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignRound1Message) ProtoMessage() {}

func (x *PreSignRound1Message) ProtoReflect() protoreflect.Message {
	mi := &file_schnorr_signing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignRound1Message.ProtoReflect.Descriptor instead.
func (*PreSignRound1Message) Descriptor() ([]byte, []int) {
	return file_schnorr_signing_proto_rawDescGZIP(), []int{0}
}

func (x *PreSignRound1Message) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

// Represents a BROADCAST message sent to all parties during Round 2 of the EdDSA TSS pre-signing protocol.
type PreSignRound2Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeCommitment  [][]byte               `protobuf:"bytes,1,rep,name=de_commitment,json=deCommitment,proto3" json:"de_commitment,omitempty"`
	Proof         [][]byte               `protobuf:"bytes,2,rep,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSignRound2Message) Reset() {
	*x = PreSignRound2Message{}
	mi := &file_schnorr_signing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSignRound2Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignRound2Message) ProtoMessage() {}

func (x *PreSignRound2Message) ProtoReflect() protoreflect.Message {
	mi := &file_schnorr_signing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignRound2Message.ProtoReflect.Descriptor instead.
func (*PreSignRound2Message) Descriptor() ([]byte, []int) {
	return file_schnorr_signing_proto_rawDescGZIP(), []int{1}
}

func (x *PreSignRound2Message) GetDeCommitment() [][]byte {
	if x != nil {
		return x.DeCommitment
	}
	return nil
}

func (x *PreSignRound2Message) GetProof() [][]byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

// Represents a BROADCAST message sent to all parties during Round 3 of the EDDSA TSS signing protocol.
type SignRound3Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S             []byte                 `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRound3Message) Reset() {
	*x = SignRound3Message{}
	mi := &file_schnorr_signing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRound3Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRound3Message) ProtoMessage() {}

func (x *SignRound3Message) ProtoReflect() protoreflect.Message {
	mi := &file_schnorr_signing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRound3Message.ProtoReflect.Descriptor instead.
func (*SignRound3Message) Descriptor() ([]byte, []int) {
	return file_schnorr_signing_proto_rawDescGZIP(), []int{2}
}

func (x *SignRound3Message) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

var File_schnorr_signing_proto protoreflect.FileDescriptor

const file_schnorr_signing_proto_rawDesc = "" +
	"\n" +
	"\x15schnorr-signing.proto\x12\x1cbinance.tsslib.eddsa.signing\"6\n" +
	"\x14PreSignRound1Message\x12\x1e\n" +
	"\n" +
	"commitment\x18\x01 \x01(\fR\n" +
	"commitment\"Q\n" +
	"\x14PreSignRound2Message\x12#\n" +
	"\rde_commitment\x18\x01 \x03(\fR\fdeCommitment\x12\x14\n" +
	"\x05proof\x18\x02 \x03(\fR\x05proof\"!\n" +
	"\x11SignRound3Message\x12\f\n" +
	"\x01s\x18\x01 \x01(\fR\x01sB\x15Z\x13tss/schnorr/signingb\x06proto3"

var (
	file_schnorr_signing_proto_rawDescOnce sync.Once
	file_schnorr_signing_proto_rawDescData []byte
)

func file_schnorr_signing_proto_rawDescGZIP() []byte {
	file_schnorr_signing_proto_rawDescOnce.Do(func() {
		file_schnorr_signing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schnorr_signing_proto_rawDesc), len(file_schnorr_signing_proto_rawDesc)))
	})
	return file_schnorr_signing_proto_rawDescData
}

var file_schnorr_signing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schnorr_signing_proto_goTypes = []any{
	(*PreSignRound1Message)(nil), // 0: binance.tsslib.eddsa.signing.PreSignRound1Message
	(*PreSignRound2Message)(nil), // 1: binance.tsslib.eddsa.signing.PreSignRound2Message
	(*SignRound3Message)(nil),    // 2: binance.tsslib.eddsa.signing.SignRound3Message
}
var file_schnorr_signing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schnorr_signing_proto_init() }
func file_schnorr_signing_proto_init() {
	if File_schnorr_signing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schnorr_signing_proto_rawDesc), len(file_schnorr_signing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schnorr_signing_proto_goTypes,
		DependencyIndexes: file_schnorr_signing_proto_depIdxs,
		MessageInfos:      file_schnorr_signing_proto_msgTypes,
	}.Build()
	File_schnorr_signing_proto = out.File
	file_schnorr_signing_proto_goTypes = nil
	file_schnorr_signing_proto_depIdxs = nil
}
