// Copyright © 2019 Binance
//
// This file is part of Binance. The full Binance copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: end-data.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Container for output signatures, mostly used for marshalling this data structure to a mobile app
type EndData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Ethereum-style recovery byte; only the first byte is relevant
	SignatureRecovery []byte `protobuf:"bytes,2,opt,name=signature_recovery,json=signatureRecovery,proto3" json:"signature_recovery,omitempty"`
	// Signature components R, S
	R []byte `protobuf:"bytes,3,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,4,opt,name=s,proto3" json:"s,omitempty"`
	// M represents the original message digest that was signed M
	M []byte `protobuf:"bytes,5,opt,name=m,proto3" json:"m,omitempty"`
	// One-Round Sign Data
	PreSignDataEcdsa *EndData_PreSignatureDataECDSA `protobuf:"bytes,10,opt,name=pre_sign_data_ecdsa,json=preSignDataEcdsa,proto3" json:"pre_sign_data_ecdsa,omitempty"`
	PreSignDataEddsa *EndData_PreSignatureDataEdDSA `protobuf:"bytes,11,opt,name=pre_sign_data_eddsa,json=preSignDataEddsa,proto3" json:"pre_sign_data_eddsa,omitempty"`
}

func (x *EndData) Reset() {
	*x = EndData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_end_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndData) ProtoMessage() {}

func (x *EndData) ProtoReflect() protoreflect.Message {
	mi := &file_end_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndData.ProtoReflect.Descriptor instead.
func (*EndData) Descriptor() ([]byte, []int) {
	return file_end_data_proto_rawDescGZIP(), []int{0}
}

func (x *EndData) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *EndData) GetSignatureRecovery() []byte {
	if x != nil {
		return x.SignatureRecovery
	}
	return nil
}

func (x *EndData) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *EndData) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *EndData) GetM() []byte {
	if x != nil {
		return x.M
	}
	return nil
}

func (x *EndData) GetPreSignDataEcdsa() *EndData_PreSignatureDataECDSA {
	if x != nil {
		return x.PreSignDataEcdsa
	}
	return nil
}

func (x *EndData) GetPreSignDataEddsa() *EndData_PreSignatureDataEdDSA {
	if x != nil {
		return x.PreSignDataEddsa
	}
	return nil
}

type EndData_PreSignatureDataECDSA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Components to produce s = sum(s_i)
	Ssid []byte   `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Pk   *ECPoint `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	R    *ECPoint `protobuf:"bytes,3,opt,name=r,proto3" json:"r,omitempty"`
	KI   []byte   `protobuf:"bytes,4,opt,name=k_i,json=kI,proto3" json:"k_i,omitempty"`
	ChiI []byte   `protobuf:"bytes,5,opt,name=chi_i,json=chiI,proto3" json:"chi_i,omitempty"`
}

func (x *EndData_PreSignatureDataECDSA) Reset() {
	*x = EndData_PreSignatureDataECDSA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_end_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndData_PreSignatureDataECDSA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndData_PreSignatureDataECDSA) ProtoMessage() {}

func (x *EndData_PreSignatureDataECDSA) ProtoReflect() protoreflect.Message {
	mi := &file_end_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndData_PreSignatureDataECDSA.ProtoReflect.Descriptor instead.
func (*EndData_PreSignatureDataECDSA) Descriptor() ([]byte, []int) {
	return file_end_data_proto_rawDescGZIP(), []int{0, 0}
}

func (x *EndData_PreSignatureDataECDSA) GetSsid() []byte {
	if x != nil {
		return x.Ssid
	}
	return nil
}

func (x *EndData_PreSignatureDataECDSA) GetPk() *ECPoint {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *EndData_PreSignatureDataECDSA) GetR() *ECPoint {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *EndData_PreSignatureDataECDSA) GetKI() []byte {
	if x != nil {
		return x.KI
	}
	return nil
}

func (x *EndData_PreSignatureDataECDSA) GetChiI() []byte {
	if x != nil {
		return x.ChiI
	}
	return nil
}

type EndData_PreSignatureDataEdDSA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Components to produce lambda
	Ssid     []byte   `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Pk       *ECPoint `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	EncodedR []byte   `protobuf:"bytes,3,opt,name=encoded_r,json=encodedR,proto3" json:"encoded_r,omitempty"`
	RI       []byte   `protobuf:"bytes,4,opt,name=r_i,json=rI,proto3" json:"r_i,omitempty"`
	R        []byte   `protobuf:"bytes,5,opt,name=r,proto3" json:"r,omitempty"`
	WI       []byte   `protobuf:"bytes,6,opt,name=w_i,json=wI,proto3" json:"w_i,omitempty"`
	A        uint64   `protobuf:"varint,7,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *EndData_PreSignatureDataEdDSA) Reset() {
	*x = EndData_PreSignatureDataEdDSA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_end_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndData_PreSignatureDataEdDSA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndData_PreSignatureDataEdDSA) ProtoMessage() {}

func (x *EndData_PreSignatureDataEdDSA) ProtoReflect() protoreflect.Message {
	mi := &file_end_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndData_PreSignatureDataEdDSA.ProtoReflect.Descriptor instead.
func (*EndData_PreSignatureDataEdDSA) Descriptor() ([]byte, []int) {
	return file_end_data_proto_rawDescGZIP(), []int{0, 1}
}

func (x *EndData_PreSignatureDataEdDSA) GetSsid() []byte {
	if x != nil {
		return x.Ssid
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetPk() *ECPoint {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetEncodedR() []byte {
	if x != nil {
		return x.EncodedR
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetRI() []byte {
	if x != nil {
		return x.RI
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetWI() []byte {
	if x != nil {
		return x.WI
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetA() uint64 {
	if x != nil {
		return x.A
	}
	return 0
}

var File_end_data_proto protoreflect.FileDescriptor

var file_end_data_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x6e, 0x64, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x74, 0x73, 0x73, 0x6c, 0x69, 0x62,
	0x1a, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5,
	0x04, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x01, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01,
	0x6d, 0x12, 0x5c, 0x0a, 0x13, 0x70, 0x72, 0x65, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x65, 0x63, 0x64, 0x73, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x74, 0x73, 0x73, 0x6c, 0x69, 0x62, 0x2e,
	0x45, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x45, 0x43, 0x44, 0x53, 0x41, 0x52, 0x10, 0x70,
	0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x63, 0x64, 0x73, 0x61, 0x12,
	0x5c, 0x0a, 0x13, 0x70, 0x72, 0x65, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x65, 0x64, 0x64, 0x73, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x62,
	0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x74, 0x73, 0x73, 0x6c, 0x69, 0x62, 0x2e, 0x45, 0x6e,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x45, 0x64, 0x44, 0x53, 0x41, 0x52, 0x10, 0x70, 0x72, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x64, 0x64, 0x73, 0x61, 0x1a, 0x83, 0x01,
	0x0a, 0x15, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x45, 0x43, 0x44, 0x53, 0x41, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x73, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x73, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x02, 0x70,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x45, 0x43, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x02, 0x70, 0x6b, 0x12, 0x16, 0x0a, 0x01, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x45, 0x43, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x01, 0x72, 0x12, 0x0f, 0x0a,
	0x03, 0x6b, 0x5f, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x6b, 0x49, 0x12, 0x13,
	0x0a, 0x05, 0x63, 0x68, 0x69, 0x5f, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63,
	0x68, 0x69, 0x49, 0x1a, 0xa0, 0x01, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x45, 0x64, 0x44, 0x53, 0x41, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x73, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x02, 0x70, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x45, 0x43, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x02, 0x70, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x52, 0x12, 0x0f, 0x0a, 0x03, 0x72, 0x5f, 0x69, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x72, 0x49, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x72, 0x12, 0x0f, 0x0a, 0x03, 0x77, 0x5f, 0x69, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x77, 0x49, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x01, 0x61, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_end_data_proto_rawDescOnce sync.Once
	file_end_data_proto_rawDescData = file_end_data_proto_rawDesc
)

func file_end_data_proto_rawDescGZIP() []byte {
	file_end_data_proto_rawDescOnce.Do(func() {
		file_end_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_end_data_proto_rawDescData)
	})
	return file_end_data_proto_rawDescData
}

var file_end_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_end_data_proto_goTypes = []any{
	(*EndData)(nil),                       // 0: binance.tsslib.EndData
	(*EndData_PreSignatureDataECDSA)(nil), // 1: binance.tsslib.EndData.PreSignatureDataECDSA
	(*EndData_PreSignatureDataEdDSA)(nil), // 2: binance.tsslib.EndData.PreSignatureDataEdDSA
	(*ECPoint)(nil),                       // 3: ECPoint
}
var file_end_data_proto_depIdxs = []int32{
	1, // 0: binance.tsslib.EndData.pre_sign_data_ecdsa:type_name -> binance.tsslib.EndData.PreSignatureDataECDSA
	2, // 1: binance.tsslib.EndData.pre_sign_data_eddsa:type_name -> binance.tsslib.EndData.PreSignatureDataEdDSA
	3, // 2: binance.tsslib.EndData.PreSignatureDataECDSA.pk:type_name -> ECPoint
	3, // 3: binance.tsslib.EndData.PreSignatureDataECDSA.r:type_name -> ECPoint
	3, // 4: binance.tsslib.EndData.PreSignatureDataEdDSA.pk:type_name -> ECPoint
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_end_data_proto_init() }
func file_end_data_proto_init() {
	if File_end_data_proto != nil {
		return
	}
	file_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_end_data_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EndData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_end_data_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EndData_PreSignatureDataECDSA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_end_data_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*EndData_PreSignatureDataEdDSA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_end_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_end_data_proto_goTypes,
		DependencyIndexes: file_end_data_proto_depIdxs,
		MessageInfos:      file_end_data_proto_msgTypes,
	}.Build()
	File_end_data_proto = out.File
	file_end_data_proto_rawDesc = nil
	file_end_data_proto_goTypes = nil
	file_end_data_proto_depIdxs = nil
}
