// Copyright © 2019 Binance
//
// This file is part of Binance. The full Binance copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: end-data.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Container for output signatures, mostly used for marshalling this data structure to a mobile app
type EndData struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Signature []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Ethereum-style recovery byte; only the first byte is relevant
	SignatureRecovery []byte `protobuf:"bytes,2,opt,name=signature_recovery,json=signatureRecovery,proto3" json:"signature_recovery,omitempty"`
	// Signature components R, S
	R []byte `protobuf:"bytes,3,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,4,opt,name=s,proto3" json:"s,omitempty"`
	// M represents the original message digest that was signed M
	M []byte `protobuf:"bytes,5,opt,name=m,proto3" json:"m,omitempty"`
	// One-Round Sign Data
	PreSignDataEcdsa *EndData_PreSignatureDataECDSA `protobuf:"bytes,10,opt,name=pre_sign_data_ecdsa,json=preSignDataEcdsa,proto3" json:"pre_sign_data_ecdsa,omitempty"`
	PreSignDataEddsa *EndData_PreSignatureDataEdDSA `protobuf:"bytes,11,opt,name=pre_sign_data_eddsa,json=preSignDataEddsa,proto3" json:"pre_sign_data_eddsa,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EndData) Reset() {
	*x = EndData{}
	mi := &file_end_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndData) ProtoMessage() {}

func (x *EndData) ProtoReflect() protoreflect.Message {
	mi := &file_end_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndData.ProtoReflect.Descriptor instead.
func (*EndData) Descriptor() ([]byte, []int) {
	return file_end_data_proto_rawDescGZIP(), []int{0}
}

func (x *EndData) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *EndData) GetSignatureRecovery() []byte {
	if x != nil {
		return x.SignatureRecovery
	}
	return nil
}

func (x *EndData) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *EndData) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *EndData) GetM() []byte {
	if x != nil {
		return x.M
	}
	return nil
}

func (x *EndData) GetPreSignDataEcdsa() *EndData_PreSignatureDataECDSA {
	if x != nil {
		return x.PreSignDataEcdsa
	}
	return nil
}

func (x *EndData) GetPreSignDataEddsa() *EndData_PreSignatureDataEdDSA {
	if x != nil {
		return x.PreSignDataEddsa
	}
	return nil
}

type EndData_PreSignatureDataECDSA struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Components to produce s = sum(s_i)
	Ssid          []byte   `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Pk            *ECPoint `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	R             *ECPoint `protobuf:"bytes,3,opt,name=r,proto3" json:"r,omitempty"`
	KI            []byte   `protobuf:"bytes,4,opt,name=k_i,json=kI,proto3" json:"k_i,omitempty"`
	ChiI          []byte   `protobuf:"bytes,5,opt,name=chi_i,json=chiI,proto3" json:"chi_i,omitempty"`
	HdDelta       []byte   `protobuf:"bytes,6,opt,name=hd_delta,json=hdDelta,proto3" json:"hd_delta,omitempty"` // HD derivation delta (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndData_PreSignatureDataECDSA) Reset() {
	*x = EndData_PreSignatureDataECDSA{}
	mi := &file_end_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndData_PreSignatureDataECDSA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndData_PreSignatureDataECDSA) ProtoMessage() {}

func (x *EndData_PreSignatureDataECDSA) ProtoReflect() protoreflect.Message {
	mi := &file_end_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndData_PreSignatureDataECDSA.ProtoReflect.Descriptor instead.
func (*EndData_PreSignatureDataECDSA) Descriptor() ([]byte, []int) {
	return file_end_data_proto_rawDescGZIP(), []int{0, 0}
}

func (x *EndData_PreSignatureDataECDSA) GetSsid() []byte {
	if x != nil {
		return x.Ssid
	}
	return nil
}

func (x *EndData_PreSignatureDataECDSA) GetPk() *ECPoint {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *EndData_PreSignatureDataECDSA) GetR() *ECPoint {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *EndData_PreSignatureDataECDSA) GetKI() []byte {
	if x != nil {
		return x.KI
	}
	return nil
}

func (x *EndData_PreSignatureDataECDSA) GetChiI() []byte {
	if x != nil {
		return x.ChiI
	}
	return nil
}

func (x *EndData_PreSignatureDataECDSA) GetHdDelta() []byte {
	if x != nil {
		return x.HdDelta
	}
	return nil
}

type EndData_PreSignatureDataEdDSA struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Components to produce lambda
	Ssid          []byte   `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Pk            *ECPoint `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	EncodedR      []byte   `protobuf:"bytes,3,opt,name=encoded_r,json=encodedR,proto3" json:"encoded_r,omitempty"`
	RI            []byte   `protobuf:"bytes,4,opt,name=r_i,json=rI,proto3" json:"r_i,omitempty"`
	R             []byte   `protobuf:"bytes,5,opt,name=r,proto3" json:"r,omitempty"`
	WI            []byte   `protobuf:"bytes,6,opt,name=w_i,json=wI,proto3" json:"w_i,omitempty"`
	A             uint64   `protobuf:"varint,7,opt,name=a,proto3" json:"a,omitempty"`
	HdDelta       []byte   `protobuf:"bytes,8,opt,name=hd_delta,json=hdDelta,proto3" json:"hd_delta,omitempty"` // HD derivation delta (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndData_PreSignatureDataEdDSA) Reset() {
	*x = EndData_PreSignatureDataEdDSA{}
	mi := &file_end_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndData_PreSignatureDataEdDSA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndData_PreSignatureDataEdDSA) ProtoMessage() {}

func (x *EndData_PreSignatureDataEdDSA) ProtoReflect() protoreflect.Message {
	mi := &file_end_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndData_PreSignatureDataEdDSA.ProtoReflect.Descriptor instead.
func (*EndData_PreSignatureDataEdDSA) Descriptor() ([]byte, []int) {
	return file_end_data_proto_rawDescGZIP(), []int{0, 1}
}

func (x *EndData_PreSignatureDataEdDSA) GetSsid() []byte {
	if x != nil {
		return x.Ssid
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetPk() *ECPoint {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetEncodedR() []byte {
	if x != nil {
		return x.EncodedR
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetRI() []byte {
	if x != nil {
		return x.RI
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetWI() []byte {
	if x != nil {
		return x.WI
	}
	return nil
}

func (x *EndData_PreSignatureDataEdDSA) GetA() uint64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *EndData_PreSignatureDataEdDSA) GetHdDelta() []byte {
	if x != nil {
		return x.HdDelta
	}
	return nil
}

var File_end_data_proto protoreflect.FileDescriptor

const file_end_data_proto_rawDesc = "" +
	"\n" +
	"\x0eend-data.proto\x12\x0ebinance.tsslib\x1a\fshared.proto\"\x9b\x05\n" +
	"\aEndData\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12-\n" +
	"\x12signature_recovery\x18\x02 \x01(\fR\x11signatureRecovery\x12\f\n" +
	"\x01r\x18\x03 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x04 \x01(\fR\x01s\x12\f\n" +
	"\x01m\x18\x05 \x01(\fR\x01m\x12\\\n" +
	"\x13pre_sign_data_ecdsa\x18\n" +
	" \x01(\v2-.binance.tsslib.EndData.PreSignatureDataECDSAR\x10preSignDataEcdsa\x12\\\n" +
	"\x13pre_sign_data_eddsa\x18\v \x01(\v2-.binance.tsslib.EndData.PreSignatureDataEdDSAR\x10preSignDataEddsa\x1a\x9e\x01\n" +
	"\x15PreSignatureDataECDSA\x12\x12\n" +
	"\x04ssid\x18\x01 \x01(\fR\x04ssid\x12\x18\n" +
	"\x02pk\x18\x02 \x01(\v2\b.ECPointR\x02pk\x12\x16\n" +
	"\x01r\x18\x03 \x01(\v2\b.ECPointR\x01r\x12\x0f\n" +
	"\x03k_i\x18\x04 \x01(\fR\x02kI\x12\x13\n" +
	"\x05chi_i\x18\x05 \x01(\fR\x04chiI\x12\x19\n" +
	"\bhd_delta\x18\x06 \x01(\fR\ahdDelta\x1a\xbb\x01\n" +
	"\x15PreSignatureDataEdDSA\x12\x12\n" +
	"\x04ssid\x18\x01 \x01(\fR\x04ssid\x12\x18\n" +
	"\x02pk\x18\x02 \x01(\v2\b.ECPointR\x02pk\x12\x1b\n" +
	"\tencoded_r\x18\x03 \x01(\fR\bencodedR\x12\x0f\n" +
	"\x03r_i\x18\x04 \x01(\fR\x02rI\x12\f\n" +
	"\x01r\x18\x05 \x01(\fR\x01r\x12\x0f\n" +
	"\x03w_i\x18\x06 \x01(\fR\x02wI\x12\f\n" +
	"\x01a\x18\a \x01(\x04R\x01a\x12\x19\n" +
	"\bhd_delta\x18\b \x01(\fR\ahdDeltaB\n" +
	"Z\b./commonb\x06proto3"

var (
	file_end_data_proto_rawDescOnce sync.Once
	file_end_data_proto_rawDescData []byte
)

func file_end_data_proto_rawDescGZIP() []byte {
	file_end_data_proto_rawDescOnce.Do(func() {
		file_end_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_end_data_proto_rawDesc), len(file_end_data_proto_rawDesc)))
	})
	return file_end_data_proto_rawDescData
}

var file_end_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_end_data_proto_goTypes = []any{
	(*EndData)(nil),                       // 0: binance.tsslib.EndData
	(*EndData_PreSignatureDataECDSA)(nil), // 1: binance.tsslib.EndData.PreSignatureDataECDSA
	(*EndData_PreSignatureDataEdDSA)(nil), // 2: binance.tsslib.EndData.PreSignatureDataEdDSA
	(*ECPoint)(nil),                       // 3: ECPoint
}
var file_end_data_proto_depIdxs = []int32{
	1, // 0: binance.tsslib.EndData.pre_sign_data_ecdsa:type_name -> binance.tsslib.EndData.PreSignatureDataECDSA
	2, // 1: binance.tsslib.EndData.pre_sign_data_eddsa:type_name -> binance.tsslib.EndData.PreSignatureDataEdDSA
	3, // 2: binance.tsslib.EndData.PreSignatureDataECDSA.pk:type_name -> ECPoint
	3, // 3: binance.tsslib.EndData.PreSignatureDataECDSA.r:type_name -> ECPoint
	3, // 4: binance.tsslib.EndData.PreSignatureDataEdDSA.pk:type_name -> ECPoint
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_end_data_proto_init() }
func file_end_data_proto_init() {
	if File_end_data_proto != nil {
		return
	}
	file_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_end_data_proto_rawDesc), len(file_end_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_end_data_proto_goTypes,
		DependencyIndexes: file_end_data_proto_depIdxs,
		MessageInfos:      file_end_data_proto_msgTypes,
	}.Build()
	File_end_data_proto = out.File
	file_end_data_proto_goTypes = nil
	file_end_data_proto_depIdxs = nil
}
