name: Go Test
on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Run Tests
        run: make test_ci
